language: ruby
rvm:
  - 2.5.1
before_script:
  - cp config/application.yml.example config/application.yml
  - cp config/database.yml.example config/database.yml
  - cp spec/fixtures/users.yml.example spec/fixtures/users.yml
  - psql -c 'create database godeploytest;' -U postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec
  - bundle exec rake assets:precompile
