---
http_interactions:
- request:
    method: get
    uri: https://source.golabs.io/api/v4/projects/3850/deployments?private_token=SpFM_1tetqXNjmQWvSZp
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Mon, 11 Jun 2018 12:17:30 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '2'
      Connection:
      - keep-alive
      Cache-Control:
      - max-age=0, private, must-revalidate
      Etag:
      - W/"d751713988987e9331980363e24189ce"
      Link:
      - <https://source.golabs.io/api/v4/projects/3850/deployments?id=3850&order_by=id&page=1&per_page=20&private_token=SpFM_1tetqXNjmQWvSZp&sort=asc>;
        rel="first", <https://source.golabs.io/api/v4/projects/3850/deployments?id=3850&order_by=id&page=1&per_page=20&private_token=SpFM_1tetqXNjmQWvSZp&sort=asc>;
        rel="last"
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Next-Page:
      - ''
      X-Page:
      - '1'
      X-Per-Page:
      - '20'
      X-Prev-Page:
      - ''
      X-Request-Id:
      - cc13e8b6-fa01-4a7f-a2c4-e90237f10607
      X-Runtime:
      - '0.025186'
      X-Total:
      - '0'
      X-Total-Pages:
      - '1'
      Strict-Transport-Security:
      - max-age=31536000
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 11 Jun 2018 12:17:30 GMT
recorded_with: VCR 4.0.0
