---
http_interactions:
- request:
    method: get
    uri: https://source.golabs.io/api/v4/projects/394?private_token=8Ai_yXWf3w7kz-kD_s9t&statistics=true
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Fri, 15 Jun 2018 09:28:32 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '1980'
      Connection:
      - keep-alive
      Cache-Control:
      - max-age=0, private, must-revalidate
      Etag:
      - W/"b9d7d89c79ae728c13b85a31e8302697"
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Request-Id:
      - b0ac3d79-e4cb-4219-92f4-a77ba20a9faf
      X-Runtime:
      - '0.062334'
      Strict-Transport-Security:
      - max-age=31536000
    body:
      encoding: UTF-8
      string: '{"id":394,"description":null,"name":"ops_portal","name_with_namespace":"gopay
        / ops_portal","path":"ops_portal","path_with_namespace":"gopay/ops_portal","created_at":"2017-01-16T19:00:30.756Z","default_branch":"master","tag_list":[],"ssh_url_to_repo":"git@source.golabs.io:gopay/ops_portal.git","http_url_to_repo":"https://source.golabs.io/gopay/ops_portal.git","web_url":"https://source.golabs.io/gopay/ops_portal","avatar_url":null,"star_count":1,"forks_count":0,"last_activity_at":"2018-06-15T09:14:40.321Z","_links":{"self":"https://source.golabs.io/api/v4/projects/394","issues":"https://source.golabs.io/api/v4/projects/394/issues","merge_requests":"https://source.golabs.io/api/v4/projects/394/merge_requests","repo_branches":"https://source.golabs.io/api/v4/projects/394/repository/branches","labels":"https://source.golabs.io/api/v4/projects/394/labels","events":"https://source.golabs.io/api/v4/projects/394/events","members":"https://source.golabs.io/api/v4/projects/394/members"},"archived":false,"visibility":"internal","resolve_outdated_diff_discussions":null,"container_registry_enabled":true,"issues_enabled":true,"merge_requests_enabled":true,"wiki_enabled":true,"jobs_enabled":true,"snippets_enabled":false,"shared_runners_enabled":true,"lfs_enabled":true,"creator_id":18,"namespace":{"id":215,"name":"gopay","path":"gopay","kind":"group","full_path":"gopay","parent_id":null},"import_status":"finished","open_issues_count":0,"public_jobs":true,"ci_config_path":null,"shared_with_groups":[{"group_id":569,"group_name":"gopay-portal-josh","group_access_level":30}],"only_allow_merge_if_pipeline_succeeds":false,"request_access_enabled":false,"only_allow_merge_if_all_discussions_are_resolved":false,"printing_merge_request_link_enabled":true,"merge_method":"merge","statistics":{"commit_count":1249,"storage_size":4167999496,"repository_size":5798625,"lfs_objects_size":0,"job_artifacts_size":4162200871},"permissions":{"project_access":null,"group_access":null}}'
    http_version: 
  recorded_at: Fri, 15 Jun 2018 09:28:32 GMT
- request:
    method: get
    uri: https://source.golabs.io/api/v4/users?private_token=8Ai_yXWf3w7kz-kD_s9t
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Fri, 15 Jun 2018 09:28:33 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '4570'
      Connection:
      - keep-alive
      Cache-Control:
      - max-age=0, private, must-revalidate
      Etag:
      - W/"45b1f26b5134c5769fcceb71b14dd023"
      Link:
      - <https://source.golabs.io/api/v4/users?active=false&blocked=false&external=false&page=2&per_page=20&private_token=8Ai_yXWf3w7kz-kD_s9t&with_custom_attributes=false>;
        rel="next", <https://source.golabs.io/api/v4/users?active=false&blocked=false&external=false&page=1&per_page=20&private_token=8Ai_yXWf3w7kz-kD_s9t&with_custom_attributes=false>;
        rel="first", <https://source.golabs.io/api/v4/users?active=false&blocked=false&external=false&page=51&per_page=20&private_token=8Ai_yXWf3w7kz-kD_s9t&with_custom_attributes=false>;
        rel="last"
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Next-Page:
      - '2'
      X-Page:
      - '1'
      X-Per-Page:
      - '20'
      X-Prev-Page:
      - ''
      X-Request-Id:
      - 751f698d-4a44-4151-9af9-9968ffb137c7
      X-Runtime:
      - '0.031373'
      X-Total:
      - '1008'
      X-Total-Pages:
      - '51'
      Strict-Transport-Security:
      - max-age=31536000
    body:
      encoding: UTF-8
      string: '[{"id":1042,"name":"mayank.j.aux","username":"mayank.j.aux","state":"active","avatar_url":"https://secure.gravatar.com/avatar/130ef9481910b8fbd54d061aca58bd25?s=80\u0026d=identicon","web_url":"https://source.golabs.io/mayank.j.aux"},{"id":1041,"name":"kashyap.k","username":"kashyap.k","state":"active","avatar_url":"https://secure.gravatar.com/avatar/657939eb7b23ae76b54ca8fcb04cb597?s=80\u0026d=identicon","web_url":"https://source.golabs.io/kashyap.k"},{"id":1040,"name":"kashif.khan","username":"kashif.khan","state":"active","avatar_url":"https://secure.gravatar.com/avatar/dd10994651237ccfc564817e718dfc60?s=80\u0026d=identicon","web_url":"https://source.golabs.io/kashif.khan"},{"id":1039,"name":"gunjan.dewan","username":"gunjan.dewan","state":"active","avatar_url":"https://secure.gravatar.com/avatar/2512136b37be09f1bc7c011661e35c88?s=80\u0026d=identicon","web_url":"https://source.golabs.io/gunjan.dewan"},{"id":1038,"name":"vinkesh.banka","username":"vinkesh.banka","state":"active","avatar_url":"https://secure.gravatar.com/avatar/80e6c75489e17773160b1c52afe5a75c?s=80\u0026d=identicon","web_url":"https://source.golabs.io/vinkesh.banka"},{"id":1037,"name":"Karuppiah","username":"karuppiah7890","state":"active","avatar_url":"https://secure.gravatar.com/avatar/0856951761e1108b3dcb735c98d1e70c?s=80\u0026d=identicon","web_url":"https://source.golabs.io/karuppiah7890"},{"id":1036,"name":"indrajati","username":"indrajati","state":"active","avatar_url":"https://secure.gravatar.com/avatar/28361b130118098a4a59dea00bfd893d?s=80\u0026d=identicon","web_url":"https://source.golabs.io/indrajati"},{"id":1035,"name":"vipul.nair","username":"vipul.nair","state":"active","avatar_url":"https://secure.gravatar.com/avatar/ae5ede5d992fab1abc02d20685086fc5?s=80\u0026d=identicon","web_url":"https://source.golabs.io/vipul.nair"},{"id":1034,"name":"duchh","username":"duchh","state":"active","avatar_url":"https://secure.gravatar.com/avatar/23084de0bc0dec957e0b65c2a2d82e2b?s=80\u0026d=identicon","web_url":"https://source.golabs.io/duchh"},{"id":1033,"name":"harish.nazief","username":"harish.nazief","state":"active","avatar_url":"https://secure.gravatar.com/avatar/133d19cdec935d939828af95e454c347?s=80\u0026d=identicon","web_url":"https://source.golabs.io/harish.nazief"},{"id":1032,"name":"almer.alana","username":"almer.alana","state":"active","avatar_url":"https://secure.gravatar.com/avatar/3c2d2952bcb5496e780a64504c1de4fa?s=80\u0026d=identicon","web_url":"https://source.golabs.io/almer.alana"},{"id":1031,"name":"didiet.noor","username":"didiet.noor","state":"active","avatar_url":"https://source.golabs.io/uploads/-/system/user/avatar/1031/avatar.png","web_url":"https://source.golabs.io/didiet.noor"},{"id":1030,"name":"faisal.ridwan","username":"faisal.ridwan","state":"active","avatar_url":"https://secure.gravatar.com/avatar/631e736ae4dbd7d25c14739f320821d1?s=80\u0026d=identicon","web_url":"https://source.golabs.io/faisal.ridwan"},{"id":1029,"name":"gunawan.santoso","username":"gunawan.santoso","state":"active","avatar_url":"https://source.golabs.io/uploads/-/system/user/avatar/1029/avatar.png","web_url":"https://source.golabs.io/gunawan.santoso"},{"id":1028,"name":"maulik.soneji","username":"maulik.soneji","state":"active","avatar_url":"https://secure.gravatar.com/avatar/401df8ee0df5a51d18871db64212a9bb?s=80\u0026d=identicon","web_url":"https://source.golabs.io/maulik.soneji"},{"id":1027,"name":"saurabh.k.aux","username":"saurabh.k.aux","state":"active","avatar_url":"https://secure.gravatar.com/avatar/742a0e30b99124b395937b2b9d8a508e?s=80\u0026d=identicon","web_url":"https://source.golabs.io/saurabh.k.aux"},{"id":1026,"name":"adit.lal","username":"adit.lal","state":"active","avatar_url":"https://secure.gravatar.com/avatar/e26c1853a00d563092e1bf9e4c900138?s=80\u0026d=identicon","web_url":"https://source.golabs.io/adit.lal"},{"id":1025,"name":"shivaprasad.bhat","username":"shivaprasad.bhat","state":"active","avatar_url":"https://secure.gravatar.com/avatar/8f66e94781d97cfac929d8188d471930?s=80\u0026d=identicon","web_url":"https://source.golabs.io/shivaprasad.bhat"},{"id":1024,"name":"alvin.adianto","username":"alvin.adianto","state":"active","avatar_url":"https://secure.gravatar.com/avatar/4aba035e4af9f0e3c77d1f9c87debf03?s=80\u0026d=identicon","web_url":"https://source.golabs.io/alvin.adianto"},{"id":1023,"name":"dong.yunfan","username":"dong.yunfan","state":"active","avatar_url":"https://secure.gravatar.com/avatar/bcb0dd2765a70f39971be8a1d4730b1f?s=80\u0026d=identicon","web_url":"https://source.golabs.io/dong.yunfan"}]'
    http_version: 
  recorded_at: Fri, 15 Jun 2018 09:28:33 GMT
- request:
    method: get
    uri: https://source.golabs.io/api/v4/projects/394/deployments?private_token=8Ai_yXWf3w7kz-kD_s9t&sort=desc
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 403
      message: Forbidden
    headers:
      Server:
      - nginx
      Date:
      - Fri, 15 Jun 2018 09:28:33 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '27'
      Connection:
      - keep-alive
      Cache-Control:
      - no-cache
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Request-Id:
      - 40ea4503-18ed-4c29-86ed-63250e075c0a
      X-Runtime:
      - '0.024723'
    body:
      encoding: UTF-8
      string: '{"message":"403 Forbidden"}'
    http_version: 
  recorded_at: Fri, 15 Jun 2018 09:28:33 GMT
recorded_with: VCR 4.0.0
