
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: godeploy
  pool: 5
<<<<<<< HEAD
  username: postgres
  password: heisenberg
=======
  username: <%= Figaro.env.db_user %>
  password: <%= Figaro.env.db_password %>
>>>>>>> 6372762118c424115bbf43428ab3258869d77265
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: godeploytest
  pool: 5
<<<<<<< HEAD
  username: postgres
  password: heisenberg
=======
  username: <%= Figaro.env.db_user %>
  password: <%= Figaro.env.db_password %>
>>>>>>> 6372762118c424115bbf43428ab3258869d77265
  timeout: 5000

production:
  <<: *default
  database: db/production.sqlite3
