
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: godeploy
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: godeploytest
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000

production:
  <<: *default
  database: db/production.sqlite3
