common: &default_settings
  license_key: 0c825c01923a57367192fdc581e81fbae189cd45
  app_name: Go-Deploy
  log_level: info

development:
  <<: *default_settings
  app_name: Go-Deploy

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: Go-Deploy

production:
  <<: *default_settings
